name: Decision Manager Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches: '**'

jobs:
  decisionManagerJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven package
        run: mvn clean -pl :decision-core,:decision-web -am package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: copy decision-core to staging folder
        run: mkdir staging && cp decision-core/target/decision-core*.jar staging
      - name: Upload decision-core artifact
        uses: actions/upload-artifact@v2
        with:
          name: decision-core
          path: staging
      - name: copy decision-web to staging folder
        run: rm decision-core/target/decision-core*.jar && cp decision-web/target/decision-web*.war staging
      - name: Upload decision-web artifact
        uses: actions/upload-artifact@v2
        with:
          name: decision-web
          path: staging
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        run: mvn -B verify sonar:sonar jacoco:prepare-agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}