name: Decision Manager Workflow

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    
jobs:
  decisionManagerJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 
    - name: Build with Maven
      run: mvn clean install -T4 org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.2 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
